spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

